### ISSUE TITLE
Error with dead-features

### ISSUE THREAD

**Issue by jmhorcas** [flamapy/bdd_metamodel#27]
There is an error in the BDD (UNED version) for the counting operations when the feature model has dead features.

The BDD returns twice the number of configurations (I think it is because is it counting dead features as possible features).
The error could be (a) in the intermediate translations of the FM to SPLOT format (Reader/Parser) required by this BDD, or (b) in the BDD solver itself.

An example of a simple model to test it can be found here: https://github.com/jmhorcas/fm_solver/blob/josemi_parallel/tests/models/ESLR/splc2021/Krieter2021.uvl

**Comment by rheradio** [comment]
I hope the error is now fixed at: https://github.com/rheradio/bdd4va

**Comment by jmhorcas** [comment]
I've tested this, but the "feature_probabilities" now crashes (i.e., get an empty result).
Not sure if this is related.
